Thrifty-Pandas/grace-shopper

- server/db/models/categories.js
- server/db/models/index.js
> new categories model #6

- server/api/users.js
- server/db/models/user.js
Get user by id route added. Only one user is returned. Currently, when the user is returned all of the user data is included.
> Route: get user by id

- server/api/users.js
- server/db/models/user.js
/api/users
Post route to create a new user in the database.
> Route: Create new user

- server/api/index.js
- server/api/products.js
- server/db/models/index.js
> adds basic routes for product

- client/store/products.js
> adds products store with fetch thunk

- server/api/products.js
> fixes issue with not exporting products router

- client/store/index.js
- client/store/products.js
> fixes products reducer

- server/api/users.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
user model previously required billing address to be notnull + isalphanumeric  but we should allow users to register and create themselves without a billing address.
also fleshed out our test specs
> adjusted user model and fixed pre-existing tests for travis

- server/api/categories.js
- server/api/index.js
will be used to populate filter options for the user
> adds categories route

- client/store/filter.js
- client/store/index.js
the store for the filter to hold the categories that the user has selected
> filter store added

- client/store/products.js
> Single product store added

- server/api/products.js
put request to update an existing instance of product
> backend api route to update an existing product

- client/components/index.js
- client/components/product-card.js
> adds product card

- client/store/index.js
- client/store/search.js
A store to hold the results of the search performed on the frontend. The results that are passed into setResults() is an array of id's.
> Search results store

- client/components/filter-form.js
- client/components/index.js
- client/routes.js
- client/store/categories.js
- client/store/index.js
> adds functional and styled Filter form component

- server/db/models/product.js
> fixes issues with the product model

- client/components/productForm.js
- client/store/products.js
- server/db/models/product.js
conditionally rendered form for add + edit product functionality
> Product formcomponent

- server/db/models/index.js
- server/db/models/order.js
> bug fixes for order model

- client/components/product-card.js
- client/components/singleProduct.js
- client/store/cart.js
- server/api/cart.js
'add to cart' button now checks if product exists in cart and adds it if it doesn't OR increments quantity of existing products by user specified quantity (default 1). this updates the redux store
> edit cart functionality added

- .vscode/launch.json
- script/seed.js
> fixes local login for seeded users

- client/components/cart-item.js
- client/components/order-item.js
- client/components/single-order.js
- client/routes.js
- client/store/orders.js
> single order component

- server/api/products.js
> fixes null image issue

- client/components/single-order.js
- client/components/user-cart.js
checkout link added to cart.
styling added.
> cart styling/ checkout link

- client/components/checkout-form.js
- client/store/orders.js
> refactor addNewOrder to fix email
